name: cangijoo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.0 <5.0.0'

dependencies:

  flutter_speed_dial: ^7.0.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.1
  google_sign_in: ^7.1.1
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0
  get: ^4.7.2
  gap: 3.0.1
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.0
  url_launcher: ^6.3.2
  flutter_slidable: ^4.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  logging: ^1.2.0

dev_dependencies:

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.svg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"



flutter:
  assets:
    - assets/icon/grocery_28dp.svg
    - assets/images/logo.svg
    - assets/images/android_light_rd_SI.svg
    - assets/icon/icons8-google-48.png
    - assets/icon/icons8-google.svg
    - assets/images/icon.png
  uses-material-design: true

